services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_USER_PASSWORD}

volumes:
  mongo-data:
